### ISSUE TITLE
yum isntall breaks beacuse `amazonlinux:latest` doesn't include autogen

### ISSUE THREAD

**Issue by beingke** [reelcrafter/audiotool-builders#2]
First of all, thanks for these Dockerfiles!

Apparently the latest version of amazonlinux doesn't include autogen, so the ```yum install``` aborts. 
To fix this you can target `amazonlinux:2` instead. 

The resulting Dockerfile would be:

```
FROM --platform=linux/amd64 amazonlinux:2
RUN yum -y update
RUN yum -y install make cmake3 autogen automake libtool gcc gcc-c++ wget tar \
  gzip zip libcurl-devel zlib-static libpng-static xz git python-devel \
  bzip2-devel which gd-devel

COPY ./build.sh build.sh
RUN chmod +x build.sh
RUN ./build.sh
```

**Comment by ffxsam** [comment]
@beingke Thanks for the heads-up! Just pushed a commit to address this.
